# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('posted_time__month',)),
        ),
    ]
