# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160612_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Formatering enligt Textile.  _kursiv_ *fet*, "länktext":url.  Tomrad för styckesbrytning (<a href="https://txstyle.org/" target="_new">mer hjälp</a>).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
